package com.fct.persistencia;

// Generated 13-sep-2013 13:34:07 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TAgentes generated by hbm2java
 */
@Entity
@Table(name = "t_agentes", uniqueConstraints = @UniqueConstraint(columnNames = "descr"))
public class TAgentes implements java.io.Serializable {

	private int oid;
	private String descr;
	private Set<TLineasContrato> TLineasContratos = new HashSet<TLineasContrato>(
			0);

	public TAgentes() {
	}

	public TAgentes(int oid) {
		this.oid = oid;
	}

	public TAgentes(int oid, String descr, Set<TLineasContrato> TLineasContratos) {
		this.oid = oid;
		this.descr = descr;
		this.TLineasContratos = TLineasContratos;
	}

	@Id
	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@Column(name = "descr", unique = true, length = 256)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAgentes")
	public Set<TLineasContrato> getTLineasContratos() {
		return this.TLineasContratos;
	}

	public void setTLineasContratos(Set<TLineasContrato> TLineasContratos) {
		this.TLineasContratos = TLineasContratos;
	}

}
