package com.fct.persistencia;

// Generated 13-sep-2013 13:34:07 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TClientes generated by hbm2java
 */
@Entity
@Table(name = "t_clientes")
public class TClientes implements java.io.Serializable {

	private Integer oid;
	private String nombre;
	private String apellidos;
	private String dni;
	private String direccion;
	private String localidad;
	private String provincia;
	private Integer cp;
	private Integer telefono1;
	private Integer telefono2;
	private String observaciones;
	private String email;
	private Set<TContratos> TContratoses = new HashSet<TContratos>(0);
	private Set<TFacturas> TFacturases = new HashSet<TFacturas>(0);

	public TClientes() {
	}

	public TClientes(String nombre, String dni, String direccion,
			String localidad, String provincia, int cp) {
		this.nombre = nombre;
		this.dni = dni;
		this.direccion = direccion;
		this.localidad = localidad;
		this.provincia = provincia;
		this.cp = cp;
	}

	public TClientes(String nombre, String apellidos, String dni,
			String direccion, String localidad, String provincia, int cp,
			Integer telefono1, Integer telefono2, String observaciones,
			Set<TContratos> TContratoses, Set<TFacturas> TFacturases) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
		this.direccion = direccion;
		this.localidad = localidad;
		this.provincia = provincia;
		this.cp = cp;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.observaciones = observaciones;
		this.TContratoses = TContratoses;
		this.TFacturases = TFacturases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "oid", unique = true, nullable = true)
	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	@Column(name = "nombre", nullable = false, length = 256)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellidos", length = 256)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "dni", nullable = true, length = 10)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "direccion", nullable = false, length = 256)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "localidad", nullable = true, length = 256)
	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	@Column(name = "provincia", nullable = true, length = 256)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "cp", nullable = true)
	public Integer getCp() {
		return this.cp;
	}

	public void setCp(Integer cp) {
		this.cp = cp;
	}

	@Column(name = "telefono1")
	public Integer getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(Integer telefono1) {
		this.telefono1 = telefono1;
	}

	@Column(name = "telefono2")
	public Integer getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(Integer telefono2) {
		this.telefono2 = telefono2;
	}

	@Column(name = "observaciones", length = 65535)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TClientes")
	public Set<TContratos> getTContratoses() {
		return this.TContratoses;
	}

	public void setTContratoses(Set<TContratos> TContratoses) {
		this.TContratoses = TContratoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TClientes")
	public Set<TFacturas> getTFacturases() {
		return this.TFacturases;
	}

	public void setTFacturases(Set<TFacturas> TFacturases) {
		this.TFacturases = TFacturases;
	}

	public String getEmail() {
		return email;
	}

	@Column(name = "email", nullable = true)
	public void setEmail(String email) {
		this.email = email;
	}
}
