package com.fct.persistencia;

// Generated 13-sep-2013 13:34:07 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TEmpresas generated by hbm2java
 */
@Entity
@Table(name = "t_empresas")
public class TEmpresas implements java.io.Serializable {

	private int oid;
	private String descripcion;
	private String ccc;
	private String info;
	private String sede;
	private boolean b;
	private boolean presupuesto;
	private boolean proforma;
	
	private Set<TFacturas> TFacturases = new HashSet<TFacturas>(0);

	public TEmpresas() {
	}

	public TEmpresas(int oid, String descripcion) {
		this.oid = oid;
		this.descripcion = descripcion;
	}

	public TEmpresas(int oid, String descripcion, Set<TFacturas> TFacturases) {
		this.oid = oid;
		this.descripcion = descripcion;
		this.TFacturases = TFacturases;
	}

	@Id
	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@Column(name = "descripcion", nullable = false, length = 256)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmpresas")
	public Set<TFacturas> getTFacturases() {
		return this.TFacturases;
	}

	public void setTFacturases(Set<TFacturas> TFacturases) {
		this.TFacturases = TFacturases;
	}

	public String getCcc() {
		return ccc;
	}

	public void setCcc(String ccc) {
		this.ccc = ccc;
	}

	@Column(name = "info", nullable = true, length = 256)
	public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Column(name = "b", nullable = false)
	public boolean isB() {
		return b;
	}

	public void setB(boolean b) {
		this.b = b;
	}

	@Column(name = "presupuesto", nullable=false)
	public boolean isPresupuesto() {
		return presupuesto;
	}

	public void setPresupuesto(boolean presupuesto) {
		this.presupuesto = presupuesto;
	}

	@Column(name = "proforma", nullable = false)
	public boolean isProforma() {
		return proforma;
	}

	public void setProforma(boolean proforma) {
		this.proforma = proforma;
	}
	
	@Column(name = "sede", nullable = true, length = 256)
	public String getSede() {
		return sede;
	}

	public void setSede(String sede) {
		this.sede = sede;
	}
}