package com.fct.persistencia;

// Generated 13-sep-2013 13:34:07 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * TFacturas generated by hbm2java
 */
@Entity
@Table(name = "t_facturas")
public class TFacturas implements java.io.Serializable {

	private Integer oid;
	private TPagos TPagos;
	private TClientes TClientes;
	private TEmpresas TEmpresas;
	private int numero;
	private Date fecha;
	private float iva;
	private List<TLineasFactura> TLineasFacturas = new LinkedList<TLineasFactura>();

	public TFacturas() {
	}

	public TFacturas(TPagos TPagos, TClientes TClientes, TEmpresas TEmpresas,
			int numero, Date fecha, float iva) {
		this.TPagos = TPagos;
		this.TClientes = TClientes;
		this.TEmpresas = TEmpresas;
		this.numero = numero;
		this.fecha = fecha;
		this.iva = iva;
	}

	public TFacturas(TPagos TPagos, TClientes TClientes, TEmpresas TEmpresas,
			int numero, Date fecha, float iva,
			List<TLineasFactura> TLineasFacturas) {
		this.TPagos = TPagos;
		this.TClientes = TClientes;
		this.TEmpresas = TEmpresas;
		this.numero = numero;
		this.fecha = fecha;
		this.iva = iva;
		this.TLineasFacturas = TLineasFacturas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "oid", unique = true, nullable = false)
	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oidpago", nullable = false)
	public TPagos getTPagos() {
		return this.TPagos;
	}

	public void setTPagos(TPagos TPagos) {
		this.TPagos = TPagos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oidclientes", nullable = false)
	public TClientes getTClientes() {
		return this.TClientes;
	}

	public void setTClientes(TClientes TClientes) {
		this.TClientes = TClientes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oidempresa", nullable = false)
	public TEmpresas getTEmpresas() {
		return this.TEmpresas;
	}

	public void setTEmpresas(TEmpresas TEmpresas) {
		this.TEmpresas = TEmpresas;
	}

	@Column(name = "numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "iva", nullable = false, precision = 12, scale = 0)
	public float getIva() {
		return this.iva;
	}

	public void setIva(float iva) {
		this.iva = iva;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TFacturas")
	@Cascade({CascadeType.ALL})
	public List<TLineasFactura> getTLineasFacturas() 
	{
		return this.TLineasFacturas;
	}

	public void setTLineasFacturas(List<TLineasFactura> TLineasFacturas) {
		this.TLineasFacturas = TLineasFacturas;
	}

}
