package com.fct.persistencia;

// Generated 13-sep-2013 13:34:07 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TPagos generated by hbm2java
 */
@Entity
@Table(name = "t_pagos")
public class TPagos implements java.io.Serializable {

	private int oid;
	private String descr;
	private Set<TFacturas> TFacturases = new HashSet<TFacturas>(0);

	public TPagos() {
	}

	public TPagos(int oid, String descr) {
		this.oid = oid;
		this.descr = descr;
	}

	public TPagos(int oid, String descr, Set<TFacturas> TFacturases) {
		this.oid = oid;
		this.descr = descr;
		this.TFacturases = TFacturases;
	}

	@Id
	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@Column(name = "descr", nullable = false, length = 256)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPagos")
	public Set<TFacturas> getTFacturases() {
		return this.TFacturases;
	}

	public void setTFacturases(Set<TFacturas> TFacturases) {
		this.TFacturases = TFacturases;
	}

}
